-- MySQL Script generated by MySQL Workbench
-- Monday 16 March 2015 09:52:20 PM IST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema csl343
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csl343
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csl343` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `csl343` ;

-- -----------------------------------------------------
-- Table `csl343`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csl343`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `phone` CHAR(10) NULL,
  `emailId` VARCHAR(50) NULL,
  `address` VARCHAR(100) NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `emailId_UNIQUE` (`emailId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csl343`.`Auction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csl343`.`Auction` (
  `idAuction` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `expctd_time` DATETIME NULL,
  `description` VARCHAR(140) NULL,
  `idUser` INT NOT NULL,
  PRIMARY KEY (`idAuction`),
  INDEX `fk_Auction_User_idx` (`idUser` ASC),
  CONSTRAINT `fk_Auction_User`
    FOREIGN KEY (`idUser`)
    REFERENCES `csl343`.`User` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csl343`.`Bid`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csl343`.`Bid` (
  `idBid` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NULL,
  `idUser` INT NULL,
  PRIMARY KEY (`idBid`),
  INDEX `fk_Bid_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Bid_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `csl343`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csl343`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csl343`.`Order` (
  `item` VARCHAR(15) NOT NULL,
  `quantity` INT UNSIGNED NULL,
  `price_per_item` DECIMAL(8,2) UNSIGNED NULL,
  `idBid` INT NOT NULL,
  PRIMARY KEY (`idBid`, `item`),
  CONSTRAINT `fk_Order_Bid1`
    FOREIGN KEY (`idBid`)
    REFERENCES `csl343`.`Bid` (`idBid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csl343`.`Placed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csl343`.`Placed` (
  `idBid` INT NOT NULL,
  `idAuction` INT NOT NULL,
  `Price` INT NOT NULL,
  `no_chances` INT NOT NULL,
  `lock` TINYINT(1) NOT NULL,
  `status` CHAR(1) NOT NULL,
  INDEX `fk_Placed_Bid1_idx` (`idBid` ASC),
  INDEX `fk_Placed_Auction1_idx` (`idAuction` ASC),
  PRIMARY KEY (`idBid`, `idAuction`),
  CONSTRAINT `fk_Placed_Bid1`
    FOREIGN KEY (`idBid`)
    REFERENCES `csl343`.`Bid` (`idBid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Placed_Auction1`
    FOREIGN KEY (`idAuction`)
    REFERENCES `csl343`.`Auction` (`idAuction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csl343`.`Feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csl343`.`Feedback` (
  `idFeedback` INT NOT NULL AUTO_INCREMENT,
  `idSender` INT NOT NULL,
  `idReceiver` INT NOT NULL,
  `stars` TINYINT(1) NOT NULL,
  `description` VARCHAR(140) NULL,
  `idAuction` INT NOT NULL,
  PRIMARY KEY (`idFeedback`),
  INDEX `fk_Feedback_User1_idx` (`idSender` ASC),
  INDEX `fk_Feedback_User2_idx` (`idReceiver` ASC),
  INDEX `fk_Feedback_Auction1_idx` (`idAuction` ASC),
  CONSTRAINT `fk_Feedback_User1`
    FOREIGN KEY (`idSender`)
    REFERENCES `csl343`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_User2`
    FOREIGN KEY (`idReceiver`)
    REFERENCES `csl343`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Feedback_Auction1`
    FOREIGN KEY (`idAuction`)
    REFERENCES `csl343`.`Auction` (`idAuction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `csl343`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csl343`.`Notification` (
  `idNotification` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `order_desc` VARCHAR(140) NOT NULL,
  `expctd_time` DATETIME NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`idNotification`),
  INDEX `fk_Notification_User1_idx` (`idUser` ASC),
  CONSTRAINT `fk_Notification_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `csl343`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
